import React from 'react';

const SQL_SCRIPT = `
-- Create the table to store news articles
CREATE TABLE public.articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  title TEXT NOT NULL,
  blurb TEXT NOT NULL,
  url TEXT NOT NULL UNIQUE,
  "sourceTitle" TEXT,
  "imageUrl" TEXT,
  "publishedDate" TEXT,
  "keyTakeaway" TEXT,
  "bulletPoints" TEXT[],
  category TEXT NOT NULL,
  year INT NOT NULL,
  month TEXT NOT NULL
);

-- Add a comment for clarity
COMMENT ON COLUMN public.articles.url IS 'The unique URL of the article to prevent duplicates.';

-- Enable Row Level Security (RLS)
ALTER TABLE public.articles ENABLE ROW LEVEL SECURITY;

-- Create a policy to allow public read access
CREATE POLICY "Enable read access for all users" ON public.articles
FOR SELECT USING (true);

-- Create a policy to allow anonymous users to add articles
CREATE POLICY "Enable insert for anonymous users" ON public.articles
FOR INSERT WITH CHECK (true);

-- Create a policy to allow anonymous users to update articles
CREATE POLICY "Enable update for anonymous users" ON public.articles
FOR UPDATE USING (true);
`.trim();

const SqlSetupInstructions: React.FC = () => {
  const [isCopied, setIsCopied] = React.useState(false);

  const handleCopy = async () => {
    try {
      await navigator.clipboard.writeText(SQL_SCRIPT);
      setIsCopied(true);
      setTimeout(() => setIsCopied(false), 2000);
    } catch (err) {
      console.error("Failed to copy script:", err);
    }
  };

  const baseButtonClasses = "absolute top-2 right-2 px-3 py-1 text-xs font-semibold text-white rounded-md focus:outline-none focus:ring-2 transition-colors duration-200";
  const copyButtonClasses = "bg-green-600 hover:bg-green-700 focus:ring-green-400";
  const copiedButtonClasses = "bg-blue-600 hover:bg-blue-700 focus:ring-blue-400";

  return (
    <div className="p-8 bg-slate-800 text-slate-200 rounded-xl shadow-2xl">
      <h2 className="text-xl font-bold text-white mb-3">Setup Instructions</h2>
      <ol className="list-decimal list-inside space-y-2 text-sm text-slate-300">
        <li>Go to your project on <a href="https://supabase.com/" target="_blank" rel="noopener noreferrer" className="text-green-400 hover:underline">Supabase.com</a>.</li>
        <li>Navigate to the <b className="text-white">SQL Editor</b> in the sidebar.</li>
        <li>Click <b className="text-white">New query</b>.</li>
        <li>Copy the script below and paste it into the editor.</li>
        <li>Click <b className="text-white">RUN</b>.</li>
      </ol>
      <div className="relative mt-4">
        <pre className="bg-slate-900 text-slate-300 p-4 rounded-lg text-xs overflow-x-auto">
          <code>{SQL_SCRIPT}</code>
        </pre>
        <button
          onClick={handleCopy}
          className={`${baseButtonClasses} ${isCopied ? copiedButtonClasses : copyButtonClasses}`}
        >
          {isCopied ? 'Copied!' : 'Copy Script'}
        </button>
      </div>
      <p className="text-xs text-slate-400 mt-3">
        This script creates the 'articles' table and sets up security policies to allow the app to read and write data.
      </p>
    </div>
  );
};

export default SqlSetupInstructions;